# Generated by Django 2.0a1 on 2017-10-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mialAddress',
            fields=[
                ('id', models.AutoField(db_column='ID', max_length=11, primary_key=True, serialize=False)),
                ('mialUserNmae', models.CharField(blank=True, db_column='mailUserName', max_length=255)),
                ('mail', models.CharField(db_column='mail', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='UID', max_length=11, primary_key=True, serialize=False)),
                ('userName', models.CharField(db_column='username', max_length=255)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('cid', models.IntegerField(db_column='CID', max_length=11)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
