# Generated by Django 2.0a1 on 2017-10-04 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addTime',
            field=models.DateTimeField(auto_now_add=True, db_column='addTime', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
