# Generated by Django 2.0a1 on 2017-10-04 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_user_addtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mialaddress',
            name='addTime',
            field=models.DateTimeField(auto_now_add=True, db_column='addTime', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mialaddress',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, db_column='updateTime', null=True),
        ),
    ]
