# Generated by Django 2.0a1 on 2017-11-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20171004_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cid',
            field=models.IntegerField(blank=True, db_column='CID'),
        ),
    ]
