# Generated by Django 2.0a1 on 2017-11-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20171119_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mialAddress',
            new_name='mailAddress',
        ),
        migrations.RenameModel(
            old_name='mialContent',
            new_name='mailContent',
        ),
    ]
