# Generated by Django 2.0a1 on 2017-11-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_auto_20171119_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcontent',
            name='mailSubject',
            field=models.CharField(db_column='subject', max_length=300, null=True),
        ),
    ]
