# Generated by Django 2.0a1 on 2017-11-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_mailcontent_mailsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='userMailAddress',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('userID', models.IntegerField(db_column='userID', help_text='用户ID')),
                ('mail', models.EmailField(db_column='email', help_text='用户Emai地址', max_length=254)),
                ('autoEmailTag', models.BooleanField(db_column='autoEmailTag', default=False, help_text='是否为默认邮箱地址')),
                ('editTime', models.DateTimeField(auto_now=True, db_column='editTime', help_text='变更时间')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_column='id', max_length=11, primary_key=True, serialize=False),
        ),
    ]
