# Generated by Django 2.0a1 on 2017-11-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_auto_20171119_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailAddress',
            fields=[
                ('id', models.AutoField(db_column='ID', max_length=11, primary_key=True, serialize=False)),
                ('emailUserNmae', models.EmailField(blank=True, db_column='emailUserName', max_length=254)),
                ('email', models.CharField(db_column='email', max_length=255)),
                ('addTime', models.DateTimeField(auto_now_add=True, db_column='addTime')),
                ('updateTime', models.DateTimeField(auto_now=True, db_column='updateTime', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='emailContent',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('emailFrom', models.EmailField(db_column='from', max_length=254, null=True)),
                ('emailTo', models.EmailField(db_column='to', max_length=254, null=True)),
                ('emailSubject', models.CharField(db_column='subject', max_length=300, null=True)),
                ('emailContent', models.TextField(db_column='Content', null=True)),
                ('addTime', models.DateTimeField(auto_now_add=True, db_column='addTime', null=True)),
                ('sendTime', models.DateTimeField(db_column='sendTime', null=True)),
                ('sendTag', models.IntegerField(db_column='sendTag', null=True)),
                ('runTime', models.DateTimeField(db_column='runTime', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='mailAddress',
        ),
        migrations.DeleteModel(
            name='mailContent',
        ),
        migrations.RenameField(
            model_name='usermailaddress',
            old_name='mail',
            new_name='email',
        ),
        migrations.AddField(
            model_name='usermailaddress',
            name='emailPassword',
            field=models.CharField(db_column='eamilPassword', default=1, max_length=255),
            preserve_default=False,
        ),
    ]
