# Generated by Django 2.0a1 on 2017-11-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_auto_20171119_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermailaddress',
            name='emailHost',
            field=models.CharField(db_column='emailHost', default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermailaddress',
            name='emailPort',
            field=models.IntegerField(blank=True, db_column='emailPort', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailcontent',
            name='runTime',
            field=models.DateTimeField(db_column='runTime', null=True, verbose_name='后台运行时间'),
        ),
    ]
