# Generated by Django 2.0a1 on 2017-11-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_auto_20171119_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontent',
            name='userID',
            field=models.IntegerField(db_column='userID', default=1, help_text='用户ID'),
            preserve_default=False,
        ),
    ]
