# Generated by Django 2.0a1 on 2017-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_emailcontent_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermailaddress',
            name='emailIntervalTime',
            field=models.IntegerField(db_column='emailIntervalTime', default=60, help_text='邮件定时发送间隔时间（S）'),
        ),
    ]
