# Generated by Django 2.0a1 on 2017-12-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_usermailaddress_emailintervaltime'),
    ]

    operations = [
        migrations.CreateModel(
            name='emaileAttachment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('emailFrom', models.EmailField(db_column='emailFrom', help_text='发件人邮件', max_length=254)),
                ('contentID', models.IntegerField(db_column='contentID', help_text='邮件内容ID')),
                ('attFileName', models.CharField(db_column='attFileName', help_text='附件文件名称', max_length=100)),
                ('attFileRemark', models.CharField(db_column='attFileRemark', max_length=100)),
            ],
        ),
    ]
